framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          '%env(APP_SECRET)%'
    router:
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%env(LOCALE)%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    php_errors:
        log: true